version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2742
      POSTGRES_DB: korbojoy
    networks:
      - freecodecamp
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      DATABASE_URL: "postgresql://postgres:2742@postgres:5432/korbojoy?schema=public"
      JWT_SECRET: "super-secret"
    networks:
      - freecodecamp
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - freecodecamp

networks:
  freecodecamp:

volumes:
  pg_data:
